name: expense_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  dropdown_button2: ^3.1.0
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^11.1.1
  google_fonts: ^8.2.1
  http: ^1.6.0
  intl: ^0.20.3
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
